package com.tgjs.dql.mymvpdemo.constants;

/**
 * Created by Administrator on 2017/9/9.
 */

public interface RequestWhatI {

    int REQUEST_WHAT_SENDCHECKNUM = 1;
    int REQUEST_WHAT_USERREGIST = 2;
    int REQUEST_WHAT_USERLOGIN = 3;
    int REQUEST_WHAT_DOWNLOAD_IDCARDFORE = 4;
    int REQUEST_WHAT_DOWNLOAD_IDCARDBACK = 5;
    int REQUEST_WHAT_DOWNLOAD_IDCARDFACE = 6;
    int REQUEST_WHAT_DOWNLOAD_LIVEFACE = 7;
    int REQUEST_WHAT_FACERECOFINZEPOST = 8;
    int REQUEST_WHAT_UPFILE = 9;
    int REQUEST_WHAT_YYSCHECK_STARTTASK = 10;
    int REQUEST_WHAT_YYSCHECK_STARTLOGIN = 11;
    int REQUEST_WHAT_YYSQUERYRESULT = 12;
    int REQUEST_WHAT_LOANRECORD = 13;
    int REQUEST_WHAT_BANKLIST = 14;
    int REQUEST_WHAT_SENDCHECKNUM1 = 15;
    int REQUEST_WHAT_BANKINFOLIST = 16;
    int REQUEST_WHAT_ADDBANKCARD = 17;
    int REQUEST_WHAT_DELETEBANKCARD = 18;
    int REQUEST_WHAT_RESETPWD_SENDCHECKNUM = 19;
    int REQUEST_WHAT_RESETPWD = 20;
    int REQUEST_WHAT_ADDCONTACT = 21;
    int REQUEST_WHAT_UPOPERATERDATA = 22;
    int REQUEST_WHAT_USERRELOGIN = 23;
    int REQUEST_WHAT_LOANAPPLY = 24;
    int REQUEST_WHAT_APPROVEPAGE = 25;
    int REQUEST_WHAT_MESSAGELIST = 26;
    int REQUEST_WHAT_BANNERLIST = 27;
    int REQUEST_WHAT_NOTICELIST = 28;
    int REQUEST_WHAT_REPAYMENT = 29;
    int REQUEST_WHAT_ENTERRELOAN = 30;
    int REQUEST_WHAT_BANKCARD_CHANGEDEFAULT = 31;
    int REQUEST_WHAT_CHECKUSERCANLOAN = 32;
    int REQUEST_WHAT_APPLYFORLOAN = 33;
    int REQUEST_WHAT_PAYFORRELOAN = 34;
    int REQUEST_WHAT_BINGBANKCARDFORLIANLIAN = 35;
    int REQUEST_WHAT_BINGBANKCARDFORLIANLIAN1 = 36;
    int REQUEST_WHAT_CONFIRMSEASMEAPPROVE = 37;
    int REQUEST_WHAT_QUERYBANKNAME = 38;
    int REQUEST_WHAT_QUERYLOANNUMBER = 39;
    int REQUEST_WHAT_QUERYLOANNUMBER_RPAYMENT = 40;
    int REQUEST_WHAT_CONFIRMPHONEAPPROVE = 41;
    int REQUEST_WHAT_QUERYLOANNUMBER_OVERDUEPAY = 42;
    int REQUEST_WHAT_QUERYBANKCARDSTATE = 43;
    int REQUEST_WHAT_UPDATEAUTHENSTATUS = 44;
    int REQUEST_WHAT_GETUSERMONEY = 45;
    int REQUEST_WHAT_APPLYLOANPAGE = 46;
    int REQUEST_WHAT_GETLOANNO = 47;
    int REQUEST_WHAT_POSTZFBINFO = 48;
    int REQUEST_WHAT_NOTIFYOPERATE = 49;
    int REQUEST_WHAT_GETREPAYMENT_YSB = 50;
    int REQUEST_WHAT_LIANLIANPAY = 51;
    int REQUEST_WHAT_YSBPAY = 52;
    int REQUEST_WHAT_UPDATELOANNO = 53;
    int REQUEST_WHAT_GETBANKNAMELIST = 54;
    int REQUEST_WHAT_EDITBANKCARD = 55;
    int REQUEST_WHAT_QUERY_AUTHSTATUS = 56;
    int REQUEST_WHAT_QUERY_AUTHSTATUS_TAOBAO = 57;
    int REQUEST_WHAT_QUERY_AUTHSTATUS_ALIPAY = 58;
    int REQUEST_WHAT_CHECK_PAYMETHOD_USEFUL = 59;
    int REQUEST_WHAT_GET_ZFBOFFICIALPARAM = 60;
    int REQUEST_WHAT_GET_CUSTOMSERVICEINFO = 61;
    int REQUEST_WHAT_INDEX = 100;
}
